# NumPy Task

***

**Programming for Data Analysis Task 2020**

*Exploration of Python's NumPy library & in particular the numpy.random package as part of the Programming for Data Analysis Module 2020*

Submission date: 22nd November 2020

- - - -

**Objectives:**

Provide detailed explanations with working examples for the following items in relation to the NumPy package:

1. Explain the overall purpose of the package.

2. Explain the use of the “Simple random data” and “Permutations” functions.

3. Explain the use and purpose of at least five “Distributions” functions.

4. Explain the use of seeds in generating pseudorandom numbers.

***

# 1.0 NumPy Package

"NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays" [1]

NumPy short for numerical python is a open source python library.

NumPy facilitates the efficient performance of mathematical functions and operations on array and matrix datastructures, NumPy is used extensively by scientists, engineers & programmers.   

The main array datastructure in Numpy is described as multidimensional or n-dimensional arrays, which  contain data of homogeneous data types i.e all data within the array is of one type such as floats, intergers etc.
Having all that data as one type allows for the performance of a wide variety of mathematical operations & calculations on the NumPy arrays.

The array datastructure is of fixed size, the number of dimensions of an array is known as the **rank** or **axes** and the number of items within an array is defined by its **shape**, which is a tuple of N non-negative integers.
In essence an array is a grid of values or data that can be easily located by means of indexing i.e each element within an array can be identified or located by calling on it's corresponding column & row index value.

![Array](https://github.com/PaulSweeney89/ProgDA-Task/blob/main/Images/Array.png?raw=true)

**Figure 1** Visual Depiction of Array Datastructure [www.oreilly.com](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html)

## 1.1 Array Creation

Replicating & exploring the data arrays depicted in Figure 1.

In [2]:
import numpy as np

# 1-Dimensional Array
one_dim = np.array([7,2,9,10])

print("1-D Array = ",one_dim)

# Ouput type to confirmn n-dimensional array type (ndarray) & element types contained within array
print("Type =", type(one_dim))
print("Element Type = ",one_dim.dtype)

# Output shape of array, number of dimensions & number of elements
print("1-D Array Shape =", one_dim.shape)
print("No. of Array Dimensions =", one_dim.ndim)
print("The array contains ",one_dim.size, "elements")

1-D Array =  [ 7  2  9 10]
Type = <class 'numpy.ndarray'>
Element Type =  int64
1-D Array Shape = (4,)
No. of Array Dimensions = 1
The array contains  4 elements


The output above shows the creation of a 1-dimensional array using the **numpy.array()** function, the input to form the array is a list conisting of 4 elements.

The type was checked to confirm that an n-dimensional array was created.

The element types within the array were also checked, confirming that the array is of homogeneous data types, i.e all intergers.

Finally the shape of the array was confirmed to be a 1-dimensional array  consisting of 1 row with 4 elements or columns.

A 1-dimensional array can be referred to as a **vector** [2].


In [5]:
# 2-Dimensional Array
two_dim = np.array([[5.2,3,4.5],
                    [9.1,0.1,0.3]])

print("2-D Array = ",two_dim)

# Ouput type to confirmn n-dimensional array type (ndarray)
print("Type =", type(two_dim))
print("Element Type = ",two_dim.dtype)

# Output shape of array, number of dimensions & number of elements
print("2-D Array Shape =", two_dim.shape)
print("No. of Array Dimensions =", two_dim.ndim)
print("The array contains ",two_dim.size, "elements")

2-D Array =  [[5.2 3.  4.5]
 [9.1 0.1 0.3]]
Type = <class 'numpy.ndarray'>
Element Type =  float64
2-D Array Shape = (2, 3)
No. of Array Dimensions = 2
The array contains  6 elements


The 2-dimensional array created above, consists of an input of 2 lists which results in an array containing 2 rows with 3 elements in each.

Note that all the element types within this array are output as floats, it can be seen that the single interger value within the array was changed to a float, confirming that all data contained within arrays are of homogeneous data types.

A 2-dimensional array can be referred to as a **matrix** [2].

In [6]:
# using np.zeros to form a 3-dimensional array
# in order to replicate the data structure shown in figure 1
z = np.zeros((4, 3, 2))
print(z)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [7]:
# 3-Dimensional Array 
three_dim = np.array([[[1, 2],[4, 3],[7, 4]],                     
                     [[2, 1],[9, 2],[7, 5]],
                     [[1, 0],[3, 4],[0, 2]],
                     [[6, 7],[9, 7],[6, 8]]])

print("3-D Array = ",three_dim)

# Ouput type to confirmn n-dimensional array type (ndarray)
print("Type =", type(three_dim))
print("Element Type = ",three_dim.dtype)

# Output shape of array, number of dimensions & number of elements
print("3-D Array Shape =", three_dim.shape)
print("No. of Array Dimensions =", three_dim.ndim)
print("The array contains ",three_dim.size, "elements")

3-D Array =  [[[1 2]
  [4 3]
  [7 4]]

 [[2 1]
  [9 2]
  [7 5]]

 [[1 0]
  [3 4]
  [0 2]]

 [[6 7]
  [9 7]
  [6 8]]]
Type = <class 'numpy.ndarray'>
Element Type =  int64
3-D Array Shape = (4, 3, 2)
No. of Array Dimensions = 3
The array contains  24 elements


Manually forming arrays consisting of 3 or more dimensions can become very cumbersome, the input will consist of a number of nested lists within lists which can be quickly become very confusing. 

In order to correctly replicate the data structure of the 3-dimensional array shown in figure 1, the **np.zeros()** function was used initially by inputting the required array shape which then outputted the correct means to which the input lists & nested lists for the 3-dimensional array should be arranged. 

A 3-dimensional or more array can be referred to as a **tensor** [2].

Other methods for array creation include:

    np.zeros()    - an array of given shape & type consisting of all zero values 
    np.ones()     - an array of given shape & type consisting of all one values 
    np.empty()    - an array of given shape & type without any values
    np.arange()   - an array of given shape & type consisting of evenly spaced values within a given interval
    np.linspace() - an array of given shape & type consisting of evenly spaced values over a given interval
    
Note: **np.arrange()** & **np.linspace()** are similar functions but use different inputs & means to determine the array.

## 1.2 NumPy Functions & Operations

The NumPy library can be used to perform many different functions & operations on arrays and datasets, including indexing & slicing of arrays for ease of data access, array shape manipulation, mathematical & arithmetic functions, logical operations, linear algebra operations and random number generation. 

The extensive list of NumPy functions, operations & more can be seen in the [NumPy Reference Manual](https://numpy.org/doc/stable/reference/index.html) which provides a brief description & outline of all functions & operations within the NumPy library. 

### Basic NumPy Operations & Functions

Examples of some basic NumPy operations & functions

**Slicing & Indexing of arrays**

In [5]:
# 1-dimensional array A
A = np.array([0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12])
print("Array A = ", A, "\n")

# Output 5th index of array A
print("Access the 5th index value of A \n","A[5] = ", A[5], "\n")

# Slicing of array A and output as new array B
B = A[1:12:3]
print("Slicing Array B \n", "B[1:12:3] = ", B)

Array A =  [ 0  1  2  3  4  5  7  8  9 10 11 12] 

Access the 5th index value of A 
 A[5] =  5 

Slicing Array B 
 B[1:12:3] =  [ 1  4  8 11]


**Reshaping & Appending Arrays**

In [9]:
# reshape array A
A = A.reshape(3,4)
print("Array A = ", A, "\n")

# appending values to form array C with shape 3 rows & 4 columns
C = np.append(B, [13, 16, 19, 21, 24, 27, 30, 33]).reshape(3,4)
print("Array C = ", C)

Array A =  [[ 0  1  2  3]
 [ 4  5  7  8]
 [ 9 10 11 12]] 

Array C =  [[ 1  4  8 11]
 [13 16 19 21]
 [24 27 30 33]]


**Mathematical Functions & Operations**

In [12]:
D = A + C * B
print("Array D = ", D, "\n")

E = np.sqrt(D)
print("Array E = ", E, "\n")

print("Sum of E =", E.sum(), "\n")
print("Max of E =", E.max())

Array D =  [[  1  17  66 124]
 [ 17  69 159 239]
 [ 33 118 251 375]] 

Array E =  [[ 1.          4.12310563  8.1240384  11.13552873]
 [ 4.12310563  8.30662386 12.60952021 15.45962483]
 [ 5.74456265 10.86278049 15.84297952 19.36491673]] 

Sum of E = 116.69678667763839 

Max of E = 19.364916731037084


Above is a very brief overview of some of the basic functionality of the NumPy Python library, it highlights the ease at which datasets can be constructed, manipulated, data accessed & how various mathematical functions & operations can be applied to dataset arrays.

The [NumPy Documentation](https://numpy.org/doc/stable/) is a great resource to expand on some of the items briefy discussed above and to further delve into the functionality & extensive use of NumPY Python Library. 

<br>

# 2.0 "Simple Random Data” & “Permutations” Functions


Simple random data is a sample subset chosen at random from a larger dataset. Each member of the simple random data subset has an equal probability of being chosen and is therefore provides an unibiased representation of the larger dataset. 

An example of simple random data would be the selection of 5 members of staff from a company of 20 to attend an award ceremony. Each member of staff will be given a number from 1 to 20, the numbers will then be added to a hat,  with 5 numbers being drawn at random, giving each staff member a equal chance of being chosen. The 5 staff members with the corresponding selected numbers are then selected to attend the ceremony.

[!Simple Random Data Sample](link)

**Figure 2** - Simple Random Data Example [www.analyticsvidhya.com](https://www.analyticsvidhya.com/blog/2019/09/data-scientists-guide-8-types-of-sampling-techniques/)

In [32]:
# a sample of containing elements numbered from 1 to 20
sample = np.arange(1,21)
print("Numbers = ", sample)

# Using NumPy to generate a simple random sample subset contain 5 elements
rg = np.random.default_rng()
random_sample = rg.choice(sample, 5)
print("Random Sample = ", random_sample)

Numbers =  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Random Sample =  [4 2 2 2 2]


In [39]:
# Provide a number of random samples
l =[]
for i in range(0, 10):
    print(type(np.random.choice(sample,5)))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## References

[1] [geeksforgeeks.org](https://www.geeksforgeeks.org/python-numpy/)

[2] [numpy.org,  Absolute Beginners Tutorial](https://numpy.org/doc/1.19/user/absolute_beginners.html)

[3] [towardsdatascience.com, The Ultimate Beginners Guide to NumPy ](https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54)

[4] [stackabuse.com, NumPy Tutorial - a Simple Example Based Tutorial](https://stackabuse.com/numpy-tutorial-a-simple-example-based-guide/)

[5] [investopedia.com, Simple Random Sample](https://www.investopedia.com/terms/s/simple-random-sample.asp)

[6] [moonbooks.org, How to Randomly Select Elements of an Array with NumPy](https://moonbooks.org/Articles/How-to-randomly-select-elements-of-an-array-with-numpy-in-python-/)