# NumPy Task

***

**Programming for Data Analysis Task 2020**

*Exploration of Python's NumPy library & in particular the numpy.random package as part of the Programming for Data Analysis Module 2020*

Submission date: 22nd November 2020

- - - -

**Objectives:**

Provide detailed explanations with working examples for the following items in relation to the NumPy package:

1. Explain the overall purpose of the package.

2. Explain the use of the “Simple random data” and “Permutations” functions.

3. Explain the use and purpose of at least five “Distributions” functions.

4. Explain the use of seeds in generating pseudorandom numbers.

***

## 1.0 NumPy Package

"NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays" [1]

NumPy facilitates the efficient performance of mathematical functions and operations on array and matrix datastructures, NumPy is used extensively by scientists, engineers & programmers.   

The main array datastructure in Numpy is described as multidimensional or n-dimensional arrays, which  contain data of homogeneous data types i.e all data within the array is of one type such as floats, intergers etc.

The array datastructure is of fixed size, the number of dimensions and items in an array is defined by its shape, which is a tuple of N non-negative integers.

[!Array](link)

**Figure 1** Visual Depiction of Array Datastructure [www.oreilly.com](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html)

## 1.1 Array Creation

Replicating & exploring the data arrays depicted in Figure 1.

In [12]:
import numpy as np

# 1-Dimensional Array
one_dim = np.array([[7,2,9,10]])

print("1-D Array = ",one_dim)

# Ouput type to confirmn n-dimensional array type (ndarray) & element types contained within array
print("Type =", type(one_dim))
print("Element Type = ",one_dim.dtype)

# Output shape of array
print("1-D Array Shape =", one_dim.shape)

1-D Array =  [[ 7  2  9 10]]
Type = <class 'numpy.ndarray'>
Element Type =  int64
1-D Array Shape = (1, 4)


The output above shows the creation of a 1-dimensional array using the **numpy.array()** function, the input to form the array is a list conisting of 4 elements.

The type was checked to confirm that an n-dimensional array was created.

The element types within the array were also checked, confirming that the array is of homogeneous data types, i.e all intergers.

Finally the shape of the array was confirmed to be a 1-dimensional array  consisting of 1 row with 4 elements or columns.

A 1-dimensional array can be referred to as a **vector** [2].


In [13]:
# 2-Dimensional Array
two_dim = np.array([[5.2,3,4.5],
                    [9.1,0.1,0.3]])

print("2-D Array = ",two_dim)

# Ouput type to confirmn n-dimensional array type (ndarray)
print("Type =", type(two_dim))
print("Element Type = ",two_dim.dtype)

# Output shape of array
print("2-D Array Shape =", two_dim.shape)

2-D Array =  [[5.2 3.  4.5]
 [9.1 0.1 0.3]]
Type = <class 'numpy.ndarray'>
Element Type =  float64
2-D Array Shape = (2, 3)


The 2-dimensional array was created above, consists of an input of 2 lists which results in an array containing 2 rows with 3 elements in each.

Note that all the element types within this array are output as floats, it can be seen that the single interger value within the array was changed to a float, to confirm that all data contained within arrays are of homogeneous data types.

A 2-dimensional array can be referred to as a **matrix** [2].

In [14]:
# using np.zeros to form a 3-dimensional array
# in order to replicate the data structure shown in figure 1
z = np.zeros((4, 3, 2))
print(z)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [15]:
# 3-Dimensional Array 
three_dim = np.array([[[1, 2],[4, 3],[7, 4]],                     
                     [[2, 1],[9, 2],[7, 5]],
                     [[1, 0],[3, 4],[0, 2]],
                     [[6, 7],[9, 7],[6, 8]]])

print("3-D Array = ",three_dim)

# Ouput type to confirmn n-dimensional array type (ndarray)
print("Type =", type(three_dim))
print("Element Type = ",three_dim.dtype)

# Output shape of array
print("3-D Array Shape =", three_dim.shape)

3-D Array =  [[[1 2]
  [4 3]
  [7 4]]

 [[2 1]
  [9 2]
  [7 5]]

 [[1 0]
  [3 4]
  [0 2]]

 [[6 7]
  [9 7]
  [6 8]]]
Type = <class 'numpy.ndarray'>
Element Type =  int64
3-D Array Shape = (4, 3, 2)


Manually forming arrays consisting of 3 or more dimensions can become very cumbersome, the input will consist of a number of nested lists within lists which can be quickly become very confusing. 

In order to correctly replicate the data structure of the 3-dimensional array shown in figure 1, the **np.zeros()** function was used initially by inputting the required array shape which then outputted the correct means to which the input lists & nested lists for the 3-dimensional array should be arranged. 

A 3-dimensional or more array can be referred to as a **tensor** [2].

## References

[1] [www.geeksforgeeks.org](https://www.geeksforgeeks.org/python-numpy/)

[2] [www.numpy.org,  Absolute Begineers Tutorial](https://numpy.org/doc/1.19/user/absolute_beginners.html)